import { Action } from "redux";

enum ActionTypes {
    ADD_INGREDIENT="ADD_INGREDIENT",
    REMOVE_INGREDIENT="REMOVE_INGREDIENT",
    SET_INGREDIENTS="SET_INGREDIENTS",
    SET_INGREDIENTS_FAILED="SET_INGREDIENTS_FAILED",
    PURCHASE_ORDER_SUCCESS="PURCHASE_ORDER_SUCCESS",
    PURCHASE_ORDER_FAILED="PURCHASE_ORDER_FAILED",
    PURCHASE_ORDER_START="PURCHASE_ORDER_START",
    PURCHASE_ORDER_INIT="PURCHASE_ORDER_INIT",
    FETCH_ORDER_START="FETCH_ORDER_START",
    FETCH_ORDER_SUCCESS="FETCH_ORDER_SUCCESS",
    FETCH_ORDER_FAIL="FETCH_ORDER_FAIL",
    AUTH_START="AUTH_START",
    AUTH_SUCCESS="AUTH_SUCCESS",
    AUTH_FAIL="AUTH_FAIL"
}

export interface MyAction<T> extends Action<T> {
    payload: {
        [key: string]: any
    };
}

export default ActionTypes;